[2023-09-22T03:11:48.071+0000] {processor.py:157} INFO - Started process (PID=6768) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:11:48.073+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:11:48.079+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:11:48.078+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:11:49.960+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:11:48.729+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:11:49.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:11:50.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 2.058 seconds
[2023-09-22T03:12:20.673+0000] {processor.py:157} INFO - Started process (PID=6830) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:12:21.191+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:12:21.197+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:12:21.197+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:12:21.449+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:12:21.447+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:12:21.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:12:21.559+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.896 seconds
[2023-09-22T03:12:52.106+0000] {processor.py:157} INFO - Started process (PID=6885) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:12:52.157+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:12:52.160+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:12:52.159+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:12:52.342+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:12:52.339+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:12:52.342+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:12:52.444+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.342 seconds
[2023-09-22T03:13:22.818+0000] {processor.py:157} INFO - Started process (PID=6940) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:13:23.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:13:23.601+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:13:23.601+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:13:23.697+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:13:23.695+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:13:23.697+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:13:23.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.016 seconds
[2023-09-22T03:13:54.184+0000] {processor.py:157} INFO - Started process (PID=6988) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:13:55.018+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:13:55.023+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:13:55.023+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:13:55.122+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:13:55.121+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:13:55.122+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:13:55.432+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.251 seconds
[2023-09-22T03:14:25.750+0000] {processor.py:157} INFO - Started process (PID=7043) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:14:25.831+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:14:25.832+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:14:25.832+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:14:25.927+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:14:25.926+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:14:25.927+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:14:26.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.455 seconds
[2023-09-22T03:14:56.240+0000] {processor.py:157} INFO - Started process (PID=7099) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:14:56.280+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:14:56.282+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:14:56.282+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:14:56.375+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:14:56.374+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:14:56.376+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:14:56.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.194 seconds
[2023-09-22T03:15:27.159+0000] {processor.py:157} INFO - Started process (PID=7154) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:15:27.210+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:15:27.212+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:15:27.212+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:15:27.305+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:15:27.303+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:15:27.305+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:15:27.405+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.249 seconds
[2023-09-22T03:15:57.951+0000] {processor.py:157} INFO - Started process (PID=7215) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:15:57.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:15:57.965+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:15:57.965+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:15:58.066+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:15:58.065+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:15:58.094+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:15:58.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.374 seconds
[2023-09-22T03:16:28.380+0000] {processor.py:157} INFO - Started process (PID=7263) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:16:28.440+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:16:28.442+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:16:28.441+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:16:28.538+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:16:28.537+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:16:28.539+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:16:28.789+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.412 seconds
[2023-09-22T03:16:59.001+0000] {processor.py:157} INFO - Started process (PID=7319) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:16:59.047+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:16:59.049+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:16:59.048+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:16:59.149+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:16:59.148+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:16:59.150+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:16:59.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.278 seconds
[2023-09-22T03:17:29.905+0000] {processor.py:157} INFO - Started process (PID=7380) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:17:29.923+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:17:29.924+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:17:29.924+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:17:30.022+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:17:30.021+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:17:30.023+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:17:30.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.297 seconds
[2023-09-22T03:18:00.491+0000] {processor.py:157} INFO - Started process (PID=7435) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:18:00.620+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:18:00.624+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:18:00.624+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:18:00.736+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:18:00.735+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:18:00.737+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:18:00.904+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.417 seconds
[2023-09-22T03:18:31.619+0000] {processor.py:157} INFO - Started process (PID=7490) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:18:31.669+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:18:31.670+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:18:31.670+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:18:31.763+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:18:31.762+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:18:31.764+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:18:31.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.229 seconds
[2023-09-22T03:19:02.312+0000] {processor.py:157} INFO - Started process (PID=7544) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:19:02.717+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:19:02.719+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:19:02.719+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:19:02.810+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:19:02.809+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:19:02.810+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:19:03.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.867 seconds
[2023-09-22T03:19:33.589+0000] {processor.py:157} INFO - Started process (PID=7599) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:19:33.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:19:33.597+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:19:33.596+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:19:33.694+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:19:33.693+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:19:33.694+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:19:33.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.187 seconds
[2023-09-22T03:20:04.129+0000] {processor.py:157} INFO - Started process (PID=7654) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:20:04.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:20:04.221+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:20:04.221+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:20:04.315+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:20:04.314+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:20:04.315+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:20:04.624+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.497 seconds
[2023-09-22T03:20:35.309+0000] {processor.py:157} INFO - Started process (PID=7709) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:20:35.641+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:20:35.647+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:20:35.646+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:20:35.741+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:20:35.740+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:20:35.742+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:20:35.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.611 seconds
[2023-09-22T03:21:06.248+0000] {processor.py:157} INFO - Started process (PID=7757) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:21:06.343+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:21:06.347+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:21:06.346+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:21:06.445+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:21:06.443+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:21:06.445+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:21:07.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.396 seconds
[2023-09-22T03:21:38.259+0000] {processor.py:157} INFO - Started process (PID=7820) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:21:38.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:21:38.290+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:21:38.290+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:21:38.386+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:21:38.384+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:21:38.386+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:21:38.468+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.212 seconds
[2023-09-22T03:22:09.034+0000] {processor.py:157} INFO - Started process (PID=7875) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:22:09.057+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:22:09.059+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:22:09.059+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:22:09.290+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:22:09.289+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:22:09.290+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:22:09.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.414 seconds
[2023-09-22T03:22:39.993+0000] {processor.py:157} INFO - Started process (PID=7930) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:22:40.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:22:40.104+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:22:40.104+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:22:40.200+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:22:40.199+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:22:40.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:22:40.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.426 seconds
[2023-09-22T03:23:10.839+0000] {processor.py:157} INFO - Started process (PID=7978) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:23:10.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:23:10.857+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:23:10.857+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:23:10.960+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:23:10.958+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:23:10.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:23:11.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.894 seconds
[2023-09-22T03:23:42.305+0000] {processor.py:157} INFO - Started process (PID=8040) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:23:42.348+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:23:42.349+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:23:42.349+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:23:42.452+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:23:42.450+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 121, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 36, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:23:42.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:23:43.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.758 seconds
[2023-09-22T03:24:06.499+0000] {processor.py:157} INFO - Started process (PID=8069) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:24:06.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:24:06.514+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:24:06.513+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:24:06.623+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:24:06.621+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:24:06.623+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:24:06.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.169 seconds
[2023-09-22T03:24:36.893+0000] {processor.py:157} INFO - Started process (PID=8124) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:24:37.833+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:24:37.835+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:24:37.834+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:24:37.933+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:24:37.931+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:24:37.933+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:24:38.045+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.155 seconds
[2023-09-22T03:25:08.226+0000] {processor.py:157} INFO - Started process (PID=8179) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:25:08.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:25:08.243+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:25:08.242+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:25:08.339+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:25:08.337+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:25:08.339+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:25:08.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.165 seconds
[2023-09-22T03:25:39.101+0000] {processor.py:157} INFO - Started process (PID=8234) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:25:39.127+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:25:39.129+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:25:39.128+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:25:39.226+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:25:39.225+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:25:39.227+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:25:39.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.195 seconds
[2023-09-22T03:26:10.072+0000] {processor.py:157} INFO - Started process (PID=8289) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:26:10.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:26:10.130+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:26:10.130+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:26:10.255+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:26:10.253+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:26:10.255+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:26:10.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.251 seconds
[2023-09-22T03:26:40.405+0000] {processor.py:157} INFO - Started process (PID=8344) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:26:40.452+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:26:40.453+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:26:40.453+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:26:40.550+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:26:40.548+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:26:40.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:26:40.670+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.268 seconds
[2023-09-22T03:27:11.161+0000] {processor.py:157} INFO - Started process (PID=8399) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:27:11.169+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:27:11.170+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:27:11.170+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:27:11.260+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:27:11.259+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:27:11.261+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:27:11.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.153 seconds
[2023-09-22T03:27:42.252+0000] {processor.py:157} INFO - Started process (PID=8454) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:27:42.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:27:42.279+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:27:42.278+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:27:42.370+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:27:42.369+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:27:42.371+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:27:42.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.707 seconds
[2023-09-22T03:28:13.575+0000] {processor.py:157} INFO - Started process (PID=8509) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:28:13.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:28:13.601+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:28:13.601+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:28:13.702+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:28:13.700+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:28:13.702+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:28:13.787+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.215 seconds
[2023-09-22T03:28:44.020+0000] {processor.py:157} INFO - Started process (PID=8564) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:28:44.032+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:28:44.035+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:28:44.034+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:28:44.124+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:28:44.122+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:28:44.124+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:28:45.556+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.541 seconds
[2023-09-22T03:29:16.244+0000] {processor.py:157} INFO - Started process (PID=8619) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:29:16.339+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:29:16.343+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:29:16.342+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:29:16.454+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:29:16.453+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:29:16.454+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:29:16.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.739 seconds
[2023-09-22T03:29:47.442+0000] {processor.py:157} INFO - Started process (PID=8674) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:29:47.445+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:29:47.447+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:29:47.446+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:29:47.550+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:29:47.548+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:29:47.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:29:48.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.859 seconds
[2023-09-22T03:30:18.374+0000] {processor.py:157} INFO - Started process (PID=8729) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:30:18.396+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:30:18.398+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:30:18.398+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:30:18.493+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:30:18.491+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:30:18.493+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:30:18.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.252 seconds
[2023-09-22T03:30:48.954+0000] {processor.py:157} INFO - Started process (PID=8784) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:30:48.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:30:48.969+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:30:48.969+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:30:49.062+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:30:49.060+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:30:49.062+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:30:49.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.596 seconds
[2023-09-22T03:31:20.380+0000] {processor.py:157} INFO - Started process (PID=8839) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:31:20.474+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:31:20.476+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:31:20.476+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:31:20.581+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:31:20.579+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:31:20.581+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:31:20.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.268 seconds
[2023-09-22T03:31:51.603+0000] {processor.py:157} INFO - Started process (PID=8894) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:31:51.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:31:51.614+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:31:51.614+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:31:51.707+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:31:51.706+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:31:51.707+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:31:51.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.169 seconds
[2023-09-22T03:32:21.890+0000] {processor.py:157} INFO - Started process (PID=8949) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:32:22.625+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:32:22.626+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:32:22.626+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:32:22.724+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:32:22.723+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:32:22.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:32:22.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.956 seconds
[2023-09-22T03:32:53.783+0000] {processor.py:157} INFO - Started process (PID=9004) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:32:53.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:32:53.804+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:32:53.804+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:32:53.898+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:32:53.896+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:32:53.898+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:32:54.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.231 seconds
[2023-09-22T03:33:24.370+0000] {processor.py:157} INFO - Started process (PID=9059) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:33:24.376+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:33:24.377+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:33:24.377+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:33:24.469+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:33:24.468+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:33:24.470+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:33:25.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.454 seconds
[2023-09-22T03:33:56.257+0000] {processor.py:157} INFO - Started process (PID=9114) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:33:56.267+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:33:56.269+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:33:56.268+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:33:56.380+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:33:56.379+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:33:56.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:33:56.445+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.191 seconds
[2023-09-22T03:34:27.033+0000] {processor.py:157} INFO - Started process (PID=9169) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:34:27.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:34:27.056+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:34:27.056+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:34:27.148+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:34:27.147+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:34:27.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:34:27.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.229 seconds
[2023-09-22T03:34:57.655+0000] {processor.py:157} INFO - Started process (PID=9224) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:34:57.708+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:34:57.711+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:34:57.710+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:34:57.814+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:34:57.812+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:34:57.814+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:34:57.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.214 seconds
[2023-09-22T03:35:28.036+0000] {processor.py:157} INFO - Started process (PID=9279) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:35:28.039+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:35:28.041+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:35:28.041+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:35:28.145+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:35:28.143+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:35:28.145+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:35:28.991+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.958 seconds
[2023-09-22T03:35:59.223+0000] {processor.py:157} INFO - Started process (PID=9334) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:35:59.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:35:59.796+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:35:59.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:35:59.902+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:35:59.900+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:35:59.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:36:00.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.879 seconds
[2023-09-22T03:36:30.507+0000] {processor.py:157} INFO - Started process (PID=9390) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:36:31.692+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:36:31.695+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:36:31.695+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:36:31.806+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:36:31.805+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:36:31.807+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:36:31.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.477 seconds
[2023-09-22T03:37:02.070+0000] {processor.py:157} INFO - Started process (PID=9445) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:37:02.283+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:37:02.284+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:37:02.284+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:37:02.382+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:37:02.381+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:37:02.382+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:37:02.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.432 seconds
[2023-09-22T03:37:32.700+0000] {processor.py:157} INFO - Started process (PID=9500) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:37:32.754+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:37:32.757+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:37:32.756+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:37:32.859+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:37:32.858+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:37:32.859+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:37:32.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.241 seconds
[2023-09-22T03:38:03.621+0000] {processor.py:157} INFO - Started process (PID=9555) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:38:03.657+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:38:03.659+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:38:03.659+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:38:03.754+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:38:03.753+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:38:03.754+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:38:04.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.791 seconds
[2023-09-22T03:38:34.542+0000] {processor.py:157} INFO - Started process (PID=9610) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:38:34.559+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:38:34.560+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:38:34.560+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:38:34.654+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:38:34.653+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:38:34.654+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:38:34.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.331 seconds
[2023-09-22T03:39:05.163+0000] {processor.py:157} INFO - Started process (PID=9665) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:39:05.191+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:39:05.194+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:39:05.193+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:39:05.298+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:39:05.297+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:39:05.299+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:39:05.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.188 seconds
[2023-09-22T03:39:35.452+0000] {processor.py:157} INFO - Started process (PID=9720) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:39:35.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:39:35.467+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:39:35.466+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:39:35.557+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:39:35.556+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:39:35.558+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:39:36.457+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.008 seconds
[2023-09-22T03:40:07.113+0000] {processor.py:157} INFO - Started process (PID=9775) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:40:07.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:40:07.189+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:40:07.189+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:40:07.297+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:40:07.296+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:40:07.298+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:40:07.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.302 seconds
[2023-09-22T03:40:37.699+0000] {processor.py:157} INFO - Started process (PID=9830) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:40:37.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:40:37.706+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:40:37.706+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:40:37.800+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:40:37.799+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:40:37.801+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:40:37.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.170 seconds
[2023-09-22T03:41:08.031+0000] {processor.py:157} INFO - Started process (PID=9885) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:41:08.287+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:41:08.291+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:41:08.291+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:41:08.383+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:41:08.382+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:41:08.384+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:41:08.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.842 seconds
[2023-09-22T03:41:39.214+0000] {processor.py:157} INFO - Started process (PID=9940) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:41:39.231+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:41:39.232+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:41:39.232+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:41:39.326+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:41:39.325+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:41:39.327+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:41:39.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.172 seconds
[2023-09-22T03:42:09.406+0000] {processor.py:157} INFO - Started process (PID=9995) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:42:09.415+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:42:09.416+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:42:09.416+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:42:09.510+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:42:09.509+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:42:09.511+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:42:09.615+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.212 seconds
[2023-09-22T03:42:40.424+0000] {processor.py:157} INFO - Started process (PID=10050) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:42:40.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:42:40.439+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:42:40.439+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:42:40.533+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:42:40.532+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:42:40.534+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:42:40.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.157 seconds
[2023-09-22T03:43:11.361+0000] {processor.py:157} INFO - Started process (PID=10105) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:43:11.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:43:11.619+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:43:11.618+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:43:11.716+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:43:11.714+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:43:11.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:43:11.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.408 seconds
[2023-09-22T03:43:42.545+0000] {processor.py:157} INFO - Started process (PID=10160) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:43:42.833+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:43:42.835+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:43:42.835+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:43:42.932+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:43:42.931+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:43:42.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:43:43.198+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.656 seconds
[2023-09-22T03:44:13.335+0000] {processor.py:157} INFO - Started process (PID=10216) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:44:13.396+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:44:13.399+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:44:13.398+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:44:13.502+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:44:13.501+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:44:13.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:44:13.567+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.234 seconds
[2023-09-22T03:44:43.772+0000] {processor.py:157} INFO - Started process (PID=10270) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:44:43.786+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:44:43.787+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:44:43.787+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:44:43.881+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:44:43.880+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:44:43.882+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:44:43.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.162 seconds
[2023-09-22T03:45:14.523+0000] {processor.py:157} INFO - Started process (PID=10325) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:45:14.555+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:45:14.557+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:45:14.557+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:45:14.658+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:45:14.657+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:45:14.659+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:45:14.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.185 seconds
[2023-09-22T03:45:44.944+0000] {processor.py:157} INFO - Started process (PID=10380) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:45:44.947+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:45:44.949+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:45:44.949+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:45:45.050+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:45:45.048+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:45:45.050+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:45:45.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.171 seconds
[2023-09-22T03:46:15.181+0000] {processor.py:157} INFO - Started process (PID=10435) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:46:15.520+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:46:15.522+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:46:15.522+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:46:15.623+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:46:15.622+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:46:15.624+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:46:15.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 0.493 seconds
[2023-09-22T03:46:46.556+0000] {processor.py:157} INFO - Started process (PID=10490) to work on /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:46:47.710+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sqs_pipeline_dag.py for tasks to queue
[2023-09-22T03:46:47.712+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:46:47.711+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:46:47.826+0000] {logging_mixin.py:151} INFO - [2023-09-22T03:46:47.825+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sqs_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 123, in <module>
    sqa_pipeline_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3817, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/sqs_pipeline_dag.py", line 38, in sqa_pipeline_dag
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-22T03:46:47.826+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sqs_pipeline_dag.py
[2023-09-22T03:46:48.054+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sqs_pipeline_dag.py took 1.501 seconds
